name: quicklinker
description: "A Flutter-based app for swiftly shortening URLs and managing them efficiently."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  provider: ^6.0.0
  connectivity_plus: ^5.0.2
  audioplayers: ^5.2.1
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/quicklinker-logo.png"

flutter_native_splash:
  color: '#4808c9'
  image: assets/icons/quicklinker-logo.png
  android_12:
    image: assets/icons/quicklinker-logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/