name: quicklinker
description: "A Flutter-based app for swiftly shortening URLs and managing them efficiently."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  provider: ^6.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  path: ^1.8.3
  flutter_dotenv: ^5.0.2
  connectivity: ^3.0.6
  audioplayers: ^5.2.1
  lottie: ^2.7.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
