name: quicklinker
description: "A Flutter-based app for swiftly shortening URLs and managing them efficiently."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  flutter_dotenv: ^5.0.2
  connectivity: ^3.0.6
  audioplayers: ^0.20.1
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
